# Generated by Django 5.0 on 2024-01-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('picode', models.IntegerField()),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=150)),
                ('landmark', models.CharField(max_length=150)),
            ],
        ),
    ]
