# Generated by Django 5.0 on 2024-01-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='landmark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(),
        ),
    ]
